server:
  port: 8080
spring:
  config:
    active:
      on-profile: prod
  application:
    name: transactionmonitor
  datasource:
    url: jdbc:h2:mem:transactionmonitor
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
jwt:
  secret: 8c7d6343-c7d4-442b-84de-0ddce17a9baa
  expirationTime: 3600000
clientorigin: https://transaction-monitor-client.azurewebsites.net